-- Create the customers table if it doesn't exist
create table if not exists customers (
  id bigint generated by default as identity primary key,
  secret_token text unique not null,
  chat_id text,
  template text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table customers enable row level security;

-- Create a policy to allow users to view their own data
-- This assumes that 'secret_token' matches the authenticated user's ID (auth.uid())
create policy "Users can view their own customer settings"
  on customers for select
  using ( secret_token = auth.uid()::text );

-- Create a policy to allow users to insert their own data
create policy "Users can insert their own customer settings"
  on customers for insert
  with check ( secret_token = auth.uid()::text );

-- Create a policy to allow users to update their own data
create policy "Users can update their own customer settings"
  on customers for update
  using ( secret_token = auth.uid()::text )
  with check ( secret_token = auth.uid()::text );

-- Grant access to the authenticated role
grant select, insert, update, delete on customers to authenticated;
grant usage on sequence customers_id_seq to authenticated;
